# Generated by Django 3.1 on 2021-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20210215_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='message',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
