# Generated by Django 3.1 on 2021-02-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20210218_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date', '-timestamp', '-last_update']},
        ),
    ]
