# Generated by Django 3.1 on 2021-04-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20210302_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='User',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.article')),
            ],
        ),
    ]
